config/routes.rb
Myrubyblog::Application.routes.draw do
  resources :post_comments

  get "pages/about"

  get "pages/contact"

  get "pages/resources"

  devise_for :admin_users, ActiveAdmin::Devise.config
  

  resources :categories

  get "categories/index"

  get "categories/edit"

  get "categories/show"

  get "categories/new"

  get "home/index"
  resources :posts
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/resources', :to => 'pages#resources'

   root :to => 'home#index'

  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,:name,:password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :posts
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :posts
end

app/models/catergory.rb
class Catergory < ActiveRecord::Base
  attr_accessible :name
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :admin_user_id, :body, :category_id, :title
  belongs_to :category
  belongs_to :admin_user
  has_many :post_comments, :dependent => :destroy
  validates :title, :presence => true
  validates_length_of :body, :minimum => 10 
end

app/models/post_comment.rb
class PostComment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :email, :name, :post, :post_id 
  validates_presence_of :name
  validates_length_of :name, :within=>2 ..20
  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :all_categories
  before_filter :site_search

  def all_categories
  	@categories = Category.all
  end

  def all_posts
  	@posts = Post.all
  end

  def site_search
  	@search = Post.search(params[:search])
	@search_posts = @search.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < InheritedResources::Base
	def create
		@post_comment = PostComment.new(params[:post_comment])

		if @post_comment.save
			flash[:notice] = 'Comment was successfully created.'
			redirect_to(@post_comment.post)
		else
			flash[:notice] = "Error creating post_comment:"
			redirect_to(@post_comment.post)
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@search = Post.search(params[:search])
		@posts = @search.all
	end
	
	def show
		@post = Post.find(params[:id])
		@user = AdminUser.all
		@post_comment = PostComment.new(:post => @post)
	end

	def new
		@post = Post.new
		@category = Catergory.all	
	end
	
	def create
		@post = Post.new(params[:post])
		if @post.save
			redirect_to posts_path, :notice => "Your post has been saved"
		else
			render "new"
		end 
	end
	
	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update_attributes(params[:post])
			redirect_to post_path, :notice =>"You post has been updated"
		else
			render "edit"
		end 
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice =>"Your post has been deleted"
	end	
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<ul>
<% @categories.each do |category| %>
<div class="post">
<li><%= link_to category.name,category %></li>
</div>
<% end %>
<ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% if  @posts.each do |post| %>
<div class="post">
	<h3><%= link_to post.title,post %></h3>
	<p><%= post.body %></p>
</div>
<% end.empty? %>
	<p>Sorry, there are no posts in this category</p>
<% end %>

<%= link_to "Back to categories",categories_path %>

app/views/home/index.html.erb
<% @posts.each do |post| %>
<div class="post">
	<h3><%= link_to post.title,post %></h3>
	<div class="entry"><%= post.body %></div>
	<div class="byline">
        <p class="meta">Posted by <%= post.admin_user.name %></p>
        <p class="links"><%= link_to "Read More",post %></p>
     </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
  <div id="page">
   <div id="page-bgtop">
    <div id="page-bgbtm">
     <div id="content">
     	<div class="flash-message">
	     	<% flash.each do |key,value| %>
				<p><%= value %></p>
			<% end %>
		</div>
     	<%= yield %><!-- main view -->
      <div style="clear: both;">&nbsp;</div> 
     </div>
     <!-- end #content -->
  	
  	<%= render "partials/sidebar" %>
     <div style="clear: both;">&nbsp;</div> 

    </div>
   </div>

  </div>
  <!-- end #page-->
  <div id="footer">
   <p>&copy; : 2015, Our movies and theatre plays app</p>
  </div>
  <!-- en #footer-->

 <!-- end #wrapper-->


</body>
</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myrubyblog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!-- <%= javascript_include_tag "application" %> -->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="post">
<h1>About Myrubyblog</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer mattis justo in turpis dignissim, id convallis eros blandit. Proin finibus diam sed volutpat condimentum. In mattis, enim quis eleifend mattis, augue diam dapibus augue, a dictum odio tellus vel nisi. Suspendisse aliquam mi sit amet justo malesuada, porttitor pharetra sapien aliquet. Integer nec augue ac nulla ultricies suscipit. Etiam vitae nulla tortor. Aliquam erat volutpat. Nulla placerat felis sit amet pulvinar euismod. Nullam luctus mauris ut erat vehicula euismod. Integer bibendum tristique molestie. Cras ut sodales urna.

Vivamus elementum, nibh vitae volutpat luctus, justo elit semper turpis, vel imperdiet augue leo vitae est. Vestibulum in volutpat purus, non vulputate enim. Ut ut rutrum mi. Donec viverra pretium velit. Morbi nec odio vitae mi aliquam luctus vitae vitae erat. Nam non semper ipsum. Quisque at facilisis elit. Vestibulum elementum orci semper est auctor mattis. Vivamus aliquet vitae sapien eu consequat.

Nulla vitae quam at ipsum iaculis egestas eget quis libero. In sit amet nunc non neque porta tincidunt ac et urna. Mauris diam nunc, lobortis sit amet tortor sit amet, egestas egestas dui. Cras nec aliquet neque. In quis volutpat mi. Praesent in ultrices nunc. Curabitur scelerisque at dolor cursus volutpat. Phasellus nec risus id sem sodales eleifend. Pellentesque volutpat ac risus quis facilisis. Donec scelerisque imperdiet leo egestas feugiat. Maecenas tempus luctus vestibulum. Duis at ipsum ut elit condimentum porta ut ut elit. Nam sit amet dui tincidunt, pharetra mauris pharetra, facilisis ex.

Quisque pulvinar diam at justo fermentum, at sodales ex dictum. Maecenas nulla dolor, porta et nulla sed, mollis convallis quam. Phasellus congue nulla erat, nec placerat ex vestibulum a. Nullam porttitor interdum ex ac ornare. Nulla eget elit vitae leo varius feugiat. Praesent dictum non dui at lobortis. Donec finibus facilisis orci vel sagittis. Sed condimentum sapien nisl.

In faucibus lorem erat, in semper magna consequat vitae. Etiam elementum vestibulum nunc vel ornare. Donec eleifend nunc non ligula malesuada, eget facilisis ex facilisis. Suspendisse volutpat nisi at libero pulvinar congue et a justo. Ut in malesuada ligula, at tincidunt sem. Duis maximus nulla in nunc dapibus lobortis ut a leo. In hac habitasse platea dictumst. Integer facilisis leo id sollicitudin faucibus. Duis scelerisque tempor neque, sed consequat tellus lobortis vitae. Nunc efficitur pharetra ligula sed fringilla. Ut laoreet suscipit nisl. In fringilla tempus tellus, sit amet cursus turpis dignissim ultrices. Morbi quis posuere magna, vel dictum ligula.</p>
</div>

app/views/pages/contact.html.erb
<div class="post">
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/resources.html.erb
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myrubyblog</title>
   <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Abel" type="text/css" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


 <div id="wrapper">
  <div id="header-wrapper">
   <div id="header">
    <div id="logo">
     <h1><a href="#">My Ruby Blog</a></h1>
     <p>Learing Ruby on Rails</p>
    </div>
    <div id="menu">
		<ul class='main-nav'>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Blog", posts_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Resources", resources_path %></li>
		</ul>
    </div>
   </div>
  </div>
</div>
  <!-- end #header -->

app/views/partials/_post_comment.html.erb
<div class="post_comment">
	<i><%=h post_comment.name %> says: </i><br />
	<%= simple_format h(post_comment.body) %>
</div>

app/views/partials/_sidebar.html.erb
    <div id="sidebar">
      <ul>
       <li>
        <div id="search">
           <%= form_for @search do |f| %>
           <%= f.text_field :title_or_body_contains %>
           <%= f.submit "Search" %>
           <% end %>    
        </div>
         <div style="clear: both;">&nbsp;</div> 
       </li>

       <li>
        <h3>Categories</h3>
        <ul>
          <% all_categories.each do |cat| %>
            <li><%= link_to cat.name,category_path(:id => cat.id) %></li>
          <% end %>
        </ul>
       </li>

      </ul>
     </div>
     <!-- end #sidebar -->

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
<div class="post">
	<h3><%= link_to post.title,post %></h3>
	<p><%= post.body %></p>
</div>
<% end %>


app/views/posts/show.html.erb
<div class="post"><h1><%= @post.title %></h1>
<small><%= @post.created_at.strftime("%b %d. %Y")%></small>
<p>Created By: <%= @post.admin_user.name %>
<p><%= @post.body %></p>
<p>Category: <%= link_to @post.category.name,category_path(:id => @post.category.id) %></p>
<p><%= link_to "Back",posts_path %></p>

<h3>Add a Comment</h3>
<%= form_for @post_comment do|f| %>

<%= f.hidden_field :post_id %>

<p>
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</p>

<p>
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</p>

<p>
	<%= f.label :body %><br />
	<%= f.text_area :body %>
</p>

<p>
	<%= f.submit "Post comment" %>
</p>
<% end %>

<%= render :partial => 'partials/post_comment', :collection => @post.post_comments %>
</div>